export const mockTodos = [
  {
    id: 1,
    title: "Add backend and database",
    description: "",
    priority: "high",
    column: "todo",
  },
  {
    id: 2,
    title: "Finish React project",
    description: "Implement responsive header and deploy to Vercel",
    priority: "medium",
    column: "in-progress",
  },
  {
    id: 3,
    title: "Add CRUD operations",
    description: "Weekly check-in call",
    priority: "low",
    column: "in-review",
  },
  {
    id: 4,
    title: "Implement delete task functionality - frontend",
    description: "",
    priority: "high",
    column: "todo",
  },
  {
    id: 5,
    title: "Implement add new task functionality - frontend",
    description: "",
    priority: "high",
    column: "done",
  },
  {
    id: 6,
    title: "Add search field and social links to header",
    description: "",
    priority: "medium",
    column: "done",
  },
  {
    id: 7,
    title: "Add header",
    description: "",
    priority: "high",
    column: "done",
  },
  {
    id: 8,
    title: "Setup react todo project managment app",
    description: "",
    priority: "high",
    column: "done",
  },
  {
    id: 9,
    title: "Add login functionality",
    description: "",
    priority: "high",
    column: "todo",
  },
  {
    id: 10,
    title: "Fix drag and drop bug",
    description: "",
    priority: "medium",
    column: "in-progress",
  }
];
